import {StyleSheet} from 'react-native';
import colors from '../../assets/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    backgroundColor: colors.secondary,
  },
  textActive: {color: colors.primary,},

  head: {
    height: 60, 
    // backgroundColor: 'powderblue',
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGrey,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 5,
    paddingBottom: 5,
  },
  headSide: {
    // backgroundColor: 'gold', 
    width:50, 
    height:50, 
    alignItems: 'center', 
    justifyContent: 'center',
  },
  headImage: {
      height:25,
      width:25,
      // backgroundColor: 'khaki',
    },
  headMiddle: {
    flex: 1,
    height: 50,
    // backgroundColor: 'orange',
  },
  headTitle:{
    flex:1,
    // backgroundColor: 'powderblue',
    justifyContent: 'center',
  },
  groupInput: {
    flex: 1,
    flexDirection: 'row',
    height: 40,
    // backgroundColor: 'orange',
    alignItems: 'center', 
    justifyContent: 'center',
    paddingLeft: 5,
    paddingRight: 5,
    borderBottomWidth:1,
    borderTopWidth:1,
    borderLeftWidth:1,
    borderRightWidth:1,
    borderRadius: 5,
    borderBottomColor: colors.lightGrey,
    borderTopColor: colors.lightGrey,
    borderLeftColor: colors.lightGrey,
    borderRightColor: colors.lightGrey,
  },
  iconInput: {
    height:25,
    width:25,
    // backgroundColor: 'khaki',
    
  },
  textInput:{
    flex: 1,
    height: 40,
    // backgroundColor: 'powderblue',
    paddingLeft: 10,
    borderLeftWidth:1,
    borderLeftColor: colors.lightGrey,
    paddingRight: 5,
    marginLeft: 5,
  },


  body: {
    flex: 10,
    alignItems: 'center',
    // backgroundColor: 'skyblue',
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 5,
    paddingBottom: 5,
  },
  favoritesGroup: {
      flex:1,
      alignItems: 'center',
      flexDirection: 'row',
      // backgroundColor: 'powderblue',
      borderBottomWidth:1,
      borderBottomColor: colors.lightGrey,
      paddingLeft: 10,
      paddingTop: 10,
      paddingBottom:10,
  },
  favorites:{
    width: 100,
    height:100,
    marginRight: 15,  
    backgroundColor: colors.lightGrey,
    borderBottomWidth:1,
    borderBottomColor: colors.lightGrey,
    borderTopWidth:1,
    borderTopColor: colors.lightGrey,
    borderLeftWidth:1,
    borderLeftColor: colors.lightGrey,
    borderRightWidth:1,
    borderRightColor: colors.lightGrey,
    borderRadius: 10,
  },
  canteenGroup: {
    alignItems: 'center',
    flexDirection: 'row',
    //backgroundColor: 'powderblue',
    borderBottomWidth:1,
    borderBottomColor: colors.lightGrey,
    borderTopWidth:1,
    borderTopColor: colors.lightGrey,
    borderLeftWidth:1,
    borderLeftColor: colors.lightGrey,
    borderRightWidth:1,
    borderRightColor: colors.lightGrey,
    borderRadius: 10,
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 5,
    paddingBottom:5,
    marginLeft:5,
    marginRight:5,
    marginBottom:5,
    marginTop:5,
  },
  canteen:{
    flex:1, 
    flexDirection: 'row',
  },
  canteenImage:{
    width: 100,
    height:100,
    backgroundColor: colors.lightGrey,
    borderBottomWidth:1,
    borderBottomColor: colors.lightGrey,
    borderTopWidth:1,
    borderTopColor: colors.lightGrey,
    borderLeftWidth:1,
    borderLeftColor: colors.lightGrey,
    borderRightWidth:1,
    borderRightColor: colors.lightGrey,
    borderRadius: 10,
  },
  canteenProfile:{
    flex:1,
    //backgroundColor: 'skyblue',
    marginLeft:10,
    marginRight:5,

  },
  canteenName: {
    fontSize: 18,
    fontWeight: 'bold',
    color:colors.black
  },
  canteenType:{
    fontSize:12,
    fontStyle: 'italic',
  },
  canteenTeenant: {
    marginTop: 30,
    fontWeight: 'bold',
    color:colors.primary,
  },

  detailGroup: {
    flex:1,
    flexDirection: 'row',
    // backgroundColor: 'powderblue',
    paddingLeft: 10,
    paddingRight:10,
    paddingTop:5,
    paddingBottom:5,
    borderBottomWidth:1,
    borderBottomColor: colors.lightGrey,

  },
  detailProfile:{
    flex:4,
    // backgroundColor: 'skyblue',
  },
  detailTenant:{
    flex:1,
    // backgroundColor: 'darkblue',
    alignItems: 'center',
    marginLeft: 10,
  },
  tenantPlace:{color: colors.primary, fontWeight: 'bold'},
  tenantNumber: {color: colors.primary, fontSize:32, fontWeight: 'bold'},


  menuGroup: {
    alignItems: 'center',
    flexDirection: 'row',
    //backgroundColor: 'powderblue',
    borderBottomWidth:1,
    borderBottomColor: colors.lightGrey,
    borderTopWidth:1,
    borderTopColor: colors.lightGrey,
    borderLeftWidth:1,
    borderLeftColor: colors.lightGrey,
    borderRightWidth:1,
    borderRightColor: colors.lightGrey,
    borderRadius: 10,
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 5,
    paddingBottom:5,
    marginLeft:5,
    marginRight:5,
    marginBottom:5,
    marginTop:5,
  },
  menu:{
    flex:1, 
    flexDirection: 'row',
  },
  menuImage:{
    width: 100,
    height:100,
    backgroundColor: colors.lightGrey,
    borderBottomWidth:1,
    borderBottomColor: colors.lightGrey,
    borderTopWidth:1,
    borderTopColor: colors.lightGrey,
    borderLeftWidth:1,
    borderLeftColor: colors.lightGrey,
    borderRightWidth:1,
    borderRightColor: colors.lightGrey,
    borderRadius: 10,
  },
  menuProfile:{
    flex:1,
    //backgroundColor: 'skyblue',
    marginLeft:10,
    marginRight:5,

  },
  menuName: {
    fontSize: 18,
    fontWeight: 'bold',
    color:colors.black
  },
  menuType:{
    fontSize:12,
    fontStyle: 'italic',
  },
  menuPrice: {
    flex:1,
    // backgroundColor: 'skyblue',
    marginTop: 30,
    fontWeight: 'bold',
    color:colors.primary,
  },
  orderButton: {
    backgroundColor:colors.green, 
    alignContent:'center', 
    justifyContent: 'center',
    width:35, 
    height:40,
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
  },
  cancelButton: {
    backgroundColor:colors.green, 
    alignContent:'center', 
    justifyContent: 'center',
    width:35, 
    height:40,
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    marginLeft:10,
  },
  orderNumber: {
    // backgroundColor: 'grey',
    alignContent:'center', 
    justifyContent: 'center',
    width:30, 
    height:40,
    borderBottomWidth:1,
    borderBottomColor: colors.lightGrey,
    paddingLeft:5,
    paddingRight:5,

  },
  orderText:{
    color: 'white', 
    fontWeight: 'bold', 
    textAlign:'center',
    fontSize: 20,
  },

  nav: {
    flexDirection: 'row',
    height: 60,
    // backgroundColor: 'steelblue',
    borderTopWidth: 1,
    borderTopColor: colors.lightGrey,
    alignItems: 'center',
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 5,
    paddingBottom: 5,
  },
  navGroup: {
    flex: 1,
    height: 50,
    // backgroundColor: colors.lightGrey,
    alignItems: 'center',
    marginLeft: 1,
    marginRight: 1,
    paddingTop: 5,
    paddingBottom: 5,
  },
  navText: {
    fontSize: 12,
    color: colors.darkGrey,
  },
  navImage: {
    height:25,
    width:25,
    // backgroundColor: 'khaki',
  },
  buttonInput: {
    flex:1,
    width:100,
    flexDirection: 'row',
    height: 50,
    backgroundColor: colors.primary,
    color: colors.secondary,
    alignItems: 'center', 
    paddingLeft: 5,
    paddingRight: 5,
    marginLeft: 30,
    marginRight:30,
    marginTop:20,
    marginBottom: 20,
    borderBottomWidth:1,
    borderTopWidth:1,
    borderLeftWidth:1,
    borderRightWidth:1,
    borderRadius: 5,
    borderBottomColor: colors.lightGrey,
    borderTopColor: colors.lightGrey,
    borderLeftColor: colors.lightGrey,
    borderRightColor: colors.lightGrey,
  },
  buttonText: {
    flex: 1,
    textAlign: 'center',
    marginLeft:20,
    marginRight:30,
    // backgroundColor: 'powderblue',
    color: colors.secondary,
    fontWeight: 'bold',
    fontSize: 20,
  },
})