import {StyleSheet} from 'react-native';
import colors from '../../assets/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    backgroundColor: colors.secondary,
  },
  textActive: {color: colors.primary,},
  textMessage: {
    color: colors.primary,
    textAlign: 'center',
    marginLeft:15, 
    marginRight: 15, 
    marginTop:15, 
    marginBottom:15
  },

  head: {
    height: 60, 
    // backgroundColor:'powderblue',
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGrey,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 5,
    paddingBottom: 5,
  },
  headSide: {
    // backgroundColor: 'gold', 
    width:50, 
    height:50, 
    alignItems: 'center', 
    justifyContent: 'center',
  },
  headImage: {
      height:25,
      width:25,
      // backgroundColor: 'khaki',
  },
  headMiddle: {
    flex: 1,
    height: 50,
    // backgroundColor: 'orange',
  },
  headTitle: {
    flex:1, 
    textAlign: 'left', 
    fontSize: 18,
  },
  groupInput: {
    flex: 1,
    flexDirection: 'row',
    height: 50,
    // backgroundColor: 'orange',
    alignItems: 'center', 
    justifyContent: 'center',
    paddingLeft: 5,
    paddingRight: 5,
    marginLeft: 15,
    marginRight:15,
    marginTop:20,
    marginBottom: 20,
    borderBottomWidth:1,
    borderTopWidth:1,
    borderLeftWidth:1,
    borderRightWidth:1,
    borderRadius: 5,
    borderBottomColor: colors.lightGrey,
    borderTopColor: colors.lightGrey,
    borderLeftColor: colors.lightGrey,
    borderRightColor: colors.lightGrey,
  },
  iconInput: {
    height:25,
    width:25,
    marginLeft:5,
    marginRight:5,
    // backgroundColor: 'khaki',
    
  },
  textInput:{
    flex: 1,
    height: 40,
    // backgroundColor: 'powderblue',
    paddingLeft: 10,
    borderLeftWidth:1,
    borderLeftColor: colors.lightGrey,
    paddingRight: 5,
    marginLeft: 5,
  },
  buttonInput: {
    flex: 1,
    flexDirection: 'row',
    height: 60,
    backgroundColor: colors.primary,
    color: colors.secondary,
    alignItems: 'center', 
    paddingLeft: 5,
    paddingRight: 5,
    marginLeft: 15,
    marginRight:15,
    marginTop:20,
    marginBottom: 20,
    borderBottomWidth:1,
    borderTopWidth:1,
    borderLeftWidth:1,
    borderRightWidth:1,
    borderRadius: 5,
    borderBottomColor: colors.lightGrey,
    borderTopColor: colors.lightGrey,
    borderLeftColor: colors.lightGrey,
    borderRightColor: colors.lightGrey,
  },
  buttonText: {
    flex: 1,
    textAlign: 'center',
    // backgroundColor: 'powderblue',
    color: colors.secondary,
    fontWeight: 'bold',
    fontSize: 18,
  },
  logoImage:{
    width:110,
    height:110,
  }, 
  logoName:{
    width:255,
    height:35,
  },
  body: {
    flex: 10,
    alignItems: 'center',
    // backgroundColor: 'skyblue',
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 5,
    paddingBottom: 5,
    marginBottom: 40, 
  },
  nav: {
    flexDirection: 'row',
    height: 60,
    // backgroundColor: 'steelblue',
    borderTopWidth: 1,
    borderTopColor: colors.lightGrey,
    alignItems: 'center',
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 5,
    paddingBottom: 5,
  },
  navGroup: {
    flex: 1,
    height: 50,
    // backgroundColor: colors.lightGrey,
    alignItems: 'center',
    marginLeft: 1,
    marginRight: 1,
    paddingTop: 5,
    paddingBottom: 5,
  },
  navText: {
    fontSize: 12,
    color: colors.darkGrey,
  },
  navImage: {
    height:25,
    width:25,
    // backgroundColor: 'khaki',
  },
})